/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stayease.view;

import stayease.dao.BookingDAO;
import stayease.dao.PaymentDAO;
import stayease.model.Booking;
import stayease.model.Payment;
import stayease.util.Session;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
/**
 *
 * @author malik
 */
import stayease.model.Hotel;
import stayease.util.ImageUtil;
import javax.swing.JOptionPane;
public class HotelDetailFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HotelDetailFrame.class.getName());
    
    /**
     * Creates new form HotelDetailFrame
     */
    private Hotel hotel;
    private final BookingDAO bookingDAO = new BookingDAO();
    private final PaymentDAO paymentDAO = new PaymentDAO();
    private java.math.BigDecimal totalBayar = java.math.BigDecimal.ZERO;

    public HotelDetailFrame() {
    initComponents();
    }
    
    public HotelDetailFrame(Hotel hotel) {
    this();
    setLocationRelativeTo(null);
    this.hotel = hotel;
    spnKamar.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
    txtTotalBayar.setEditable(false);
    txtKembalian.setEditable(false);
    tampilkanDetail();
    hitungTotal();

    spnKamar.addChangeListener(e -> hitungTotal());

    dcCheckIn.getDateEditor().addPropertyChangeListener(e -> {
        if ("date".equals(e.getPropertyName())) hitungTotal();
    });
    dcCheckOut.getDateEditor().addPropertyChangeListener(e -> {
        if ("date".equals(e.getPropertyName())) hitungTotal();
    });

    txtUangBayar.getDocument().addDocumentListener(new DocumentListener() {
        @Override public void insertUpdate(DocumentEvent e)  { hitungKembalian(); }
        @Override public void removeUpdate(DocumentEvent e)  { hitungKembalian(); }
        @Override public void changedUpdate(DocumentEvent e) { hitungKembalian(); }
    });
}

/** Isi komponen dari data hotel (baris tabel hotels). */
    private void tampilkanDetail() {
    lblNama.setText(hotel.getNama());
    lblLokasi.setText(hotel.getLokasi());
    txtDeskripsi.setText(hotel.getDeskripsi());
    txtDeskripsi.setEditable(false);
    lblHarga.setText("Rp " + hotel.getHarga().toPlainString() + " / Night");
    txtTotalBayar.setText(hotel.getHarga().toPlainString());
    ImageUtil.tampilkanGambar(lblGambar, hotel.getGambar());
    }
    
    private void hitungTotal() {
    int kamar = (int) spnKamar.getValue();
    long malam = 1; 

    java.util.Date in  = dcCheckIn.getDate();
    java.util.Date out = dcCheckOut.getDate();
    if (in != null && out != null) {
        java.time.LocalDate ci = in.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        java.time.LocalDate co = out.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        long selisih = java.time.temporal.ChronoUnit.DAYS.between(ci, co);
        if (selisih >= 1) {
            malam = selisih;
        }
    }

    totalBayar = hotel.getHarga()
            .multiply(java.math.BigDecimal.valueOf(kamar))
            .multiply(java.math.BigDecimal.valueOf(malam));
    txtTotalBayar.setText(totalBayar.toPlainString());
    hitungKembalian();
}
    private void hitungKembalian() {
    String s = txtUangBayar.getText().trim();
    if (s.isEmpty()) { txtKembalian.setText(""); return; }
    try {
        java.math.BigDecimal uang = new java.math.BigDecimal(s);
        txtKembalian.setText(uang.subtract(totalBayar).toPlainString());
    } catch (NumberFormatException e) {
        txtKembalian.setText("");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblLokasi = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        dcCheckIn = new com.toedter.calendar.JDateChooser();
        dcCheckOut = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnKamar = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUangBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBooking = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNama.setText("jLabel1");

        lblLokasi.setText("jLabel2");

        lblHarga.setText("jLabel3");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtDeskripsi);

        jLabel4.setText("Hotel Data");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel5.setText("Check in");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel6.setText("Check out");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel7.setText("Number of Rooms");

        jLabel8.setText("Payment");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel9.setText("Total Amout Due");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel10.setText("Cash");

        txtUangBayar.addActionListener(this::txtUangBayarActionPerformed);

        txtKembalian.addActionListener(this::txtKembalianActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel11.setText("Change");

        btnBooking.setText("Booking Process");
        btnBooking.addActionListener(this::btnBookingActionPerformed);

        btnKembali.setText("<- Back");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLokasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(spnKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(dcCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLokasi)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHarga)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(btnBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
    java.util.Date in  = dcCheckIn.getDate();
    java.util.Date out = dcCheckOut.getDate();
    if (in == null || out == null) {
        JOptionPane.showMessageDialog(this, "Please select check-in and check-out dates.");
        return;
    }

    LocalDate checkIn  = in.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate checkOut = out.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

    if (!checkOut.isAfter(checkIn)) {
        JOptionPane.showMessageDialog(this, "Check-out date must be after check-in date.");
        return;
    }
    if (checkIn.isBefore(LocalDate.now())) {
        JOptionPane.showMessageDialog(this, "Check-in date cannot be in the past.");
        return;
    }
    if (totalBayar.signum() <= 0) {
        JOptionPane.showMessageDialog(this, "Total amount is invalid.");
        return;
    }

    String s = txtUangBayar.getText().trim();
    if (s.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the payment amount.");
        return;
    }

    java.math.BigDecimal uang;
    try {
        uang = new java.math.BigDecimal(s);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Payment amount must be a number.");
        return;
    }

    if (uang.compareTo(totalBayar) < 0) {
        JOptionPane.showMessageDialog(this, "Insufficient payment. Short by: Rp "
                + totalBayar.subtract(uang).toPlainString());
        return;
    }

    java.math.BigDecimal kembalian = uang.subtract(totalBayar);
    txtKembalian.setText(kembalian.toPlainString());

    int konfirm = JOptionPane.showConfirmDialog(this,
            "Confirm booking?\n"
            + "Hotel     : " + hotel.getNama() + "\n"
            + "Check-in  : " + checkIn + "\n"
            + "Check-out : " + checkOut + "\n"
            + "Rooms     : " + spnKamar.getValue() + "\n"
            + "Total     : Rp " + totalBayar.toPlainString() + "\n"
            + "Cash      : Rp " + uang.toPlainString() + "\n"
            + "Change    : Rp " + kembalian.toPlainString(),
            "Confirm Booking", JOptionPane.YES_NO_OPTION);

    if (konfirm != JOptionPane.YES_OPTION) return;

    Booking booking = new Booking(
            Session.getUserId(),
            hotel.getHotelId(),
            checkIn,
            checkOut,
            (int) spnKamar.getValue(),
            totalBayar,
            "Paid"
    );

    int bookingId = bookingDAO.insert(booking);
    if (bookingId < 0) {
        JOptionPane.showMessageDialog(this, "Booking failed. Please try again.",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Payment payment = new Payment(bookingId, uang, kembalian);
        paymentDAO.insert(payment);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Booking saved but payment record failed:\n" + e.getMessage(),
                "Warning", JOptionPane.WARNING_MESSAGE);
    }

    JOptionPane.showMessageDialog(this,
            "Booking successful!\nChange: Rp " + kembalian.toPlainString(),
            "Success", JOptionPane.INFORMATION_MESSAGE);

    new UserFrame().setVisible(true);
    dispose();
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
    new UserFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtUangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangBayarActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HotelDetailFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnKembali;
    private com.toedter.calendar.JDateChooser dcCheckIn;
    private com.toedter.calendar.JDateChooser dcCheckOut;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblNama;
    private javax.swing.JSpinner spnKamar;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtUangBayar;
    // End of variables declaration//GEN-END:variables
}
