/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stayease.view;

/**
 *
 * @author malik
 */
import stayease.dao.UserDAO;
import stayease.model.User;
import stayease.model.Person;    // [OOP ADDITION] superclass — used as instanceof target
import stayease.model.Admin;     // [OOP ADDITION] subclass of Person
import stayease.model.Customer;  // [OOP ADDITION] subclass of Person
import stayease.util.Session;
import javax.swing.JOptionPane;
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    setLocationRelativeTo(null);
    setSize(749, 485);
    setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkShowPassword = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(749, 451));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 60, -1));

        btnLogin.setBackground(new java.awt.Color(0, 51, 153));
        btnLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 230, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 60, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Don't have an account?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 130, -1));

        lblRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 204, 51));
        lblRegister.setText("Register");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("StayEase");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 260, 50));

        chkShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        chkShowPassword.setText("Show Password");
        chkShowPassword.addActionListener(this::chkShowPasswordActionPerformed);
        getContentPane().add(chkShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 120, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sign in to your account to continue");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 210, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 466, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icon.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 50));

        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 230, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Welcome back");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 140, 20));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 230, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background/login-form.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword());

    //Validasi tidak boleh kosong
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "You must enter your username and password.",
                "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    //Cek ke database lewat UserDAO
    UserDAO userDAO = new UserDAO();
    User user = userDAO.login(username, password);

    //Validasi hasil login
    if (user == null) {
        JOptionPane.showMessageDialog(this, "Incorrect username or password.",
                "Login Failed", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Save session — unchanged from original
    Session.login(user.getUserId(), user.getUsername(), user.getRole());

    // ── [OOP ADDITION] Inheritance + instanceof + Casting ─────────────────
    // Build a Person object (superclass reference) whose runtime type is
    // either Admin or Customer depending on the logged-in user's role.
    Person person = createPerson(user);  // returns Admin or Customer (both extend Person)

    // instanceof checks the actual runtime type of the object.
    // Casting converts the Person reference to the specific subclass type
    // so we can access subclass-specific methods (getAdminLevel, getMemberType).
    if (person instanceof Admin) {
        Admin admin = (Admin) person;           // cast Person → Admin
        System.out.println("[LOGIN] " + admin.getInfo());  // calls super.getInfo() inside Admin
        new AdminFrames().setVisible(true);     // navigate to admin dashboard

    } else if (person instanceof Customer) {
        Customer customer = (Customer) person;  // cast Person → Customer
        System.out.println("[LOGIN] " + customer.getInfo()); // calls super.getInfo() inside Customer
        new UserFrame().setVisible(true);       // navigate to user dashboard
    }
    // ── End of OOP ADDITION block ─────────────────────────────────────────

    this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        if (chkShowPassword.isSelected()) {
        txtPassword.setEchoChar((char) 0);   
    } else {
        txtPassword.setEchoChar('•');        
    }
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
    new RegisterFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lblRegisterMouseClicked

    // ── [OOP ADDITION] Helper: build a Person subclass from a logged-in User ──
    /**
     * Converts a User object (returned by UserDAO) into the correct Person subclass.
     *
     * Role "admin"  →  new Admin(...)    — Admin    extends Person
     * Any other role →  new Customer(...)— Customer extends Person
     *
     * The result is stored as a Person reference (superclass) so that instanceof
     * can be used to determine the actual runtime type at the call site.
     *
     * Inside both Admin and Customer constructors, super(id, username, noTelepon)
     * is called to pass the common data up to the Person superclass constructor.
     *
     * @param user the User object returned by UserDAO.login()
     * @return an Admin or Customer instance (both are subclasses of Person)
     */
    private Person createPerson(User user) {
        if ("admin".equalsIgnoreCase(user.getRole())) {
            // Admin constructor calls super(id, username, noTelepon) → Person
            return new Admin(user.getUserId(), user.getUsername(), user.getNoTelepon());
        } else {
            // Customer constructor calls super(id, username, noTelepon) → Person
            return new Customer(user.getUserId(), user.getUsername(), user.getNoTelepon());
        }
    }
    // ── End of OOP ADDITION helper ────────────────────────────────────────────

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
