/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stayease.view;

/**
 *
 * @author malik
 */
import stayease.dao.UserDAO;
import stayease.model.User;
import stayease.util.Session;
import javax.swing.JOptionPane;
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    setLocationRelativeTo(null);
    }
    public User login(String username, String password) {
    String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, username);
        ps.setString(2, password);

        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                User u = new User();
                u.setUserId(rs.getInt("user_id"));
                u.setNama(rs.getString("nama"));
                u.setUsername(rs.getString("username"));
                u.setRole(rs.getString("role"));
                u.setEmail(rs.getString("email"));
                u.setNoTelepon(rs.getString("no_telepon"));
                return u;   // login cocok
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return null;            // tidak ditemukan = login gagal
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkShowPassword = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(749, 451));
        setMinimumSize(new java.awt.Dimension(749, 451));
        setPreferredSize(new java.awt.Dimension(749, 451));
        setResizable(false);
        getContentPane().setLayout(null);

        btnLogin.setBackground(new java.awt.Color(0, 51, 153));
        btnLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        getContentPane().add(btnLogin);
        btnLogin.setBounds(450, 300, 230, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 150, 60, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 210, 60, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Don't have an account?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 340, 130, 16);

        lblRegister.setForeground(new java.awt.Color(255, 204, 51));
        lblRegister.setText("Register");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegister);
        lblRegister.setBounds(600, 340, 50, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("StayEase");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 30, 260, 50);

        chkShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        chkShowPassword.setText("Show Password");
        chkShowPassword.addActionListener(this::chkShowPasswordActionPerformed);
        getContentPane().add(chkShowPassword);
        chkShowPassword.setBounds(450, 270, 120, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sign in to your account to continue");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 110, 210, 16);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 60, 0, 0);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 30, 50, 50);

        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(450, 170, 230, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Welcome back");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 90, 140, 20);

        txtPassword.setText("jPasswordField1");
        getContentPane().add(txtPassword);
        txtPassword.setBounds(450, 230, 230, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-form.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-10, -10, 749, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword());

    // Kondisi 1: ada kolom kosong
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return;
    }

    UserDAO dao = new UserDAO();
    User user = dao.getByUsername(username);

    // Kondisi 2: username tidak terdaftar
    if (user == null) {
        JOptionPane.showMessageDialog(this, "Anda harus register terlebih dahulu!");
        return;
    }

    // Kondisi 3: password salah
    if (!user.getPassword().equals(password)) {
        JOptionPane.showMessageDialog(this, "Username atau Password salah!");
        return;
    }

    // Login berhasil → simpan ke Session
    Session.login(user.getUserId(), user.getNama(), user.getRole());

    // Kondisi 4 & 5: navigasi berdasarkan role
    if (Session.isAdmin()) {
        JOptionPane.showMessageDialog(this, "Login Admin Berhasil!");
        new AdminDashboardFrame().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Halo, " + user.getNama() + "!");
        new UserDashboardFrame().setVisible(true);
    }
    this.dispose(); // tutup LoginFrame
    }//GEN-LAST:event_btnLoginActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        if (chkShowPassword.isSelected()) {
        txtPassword.setEchoChar((char) 0);   // tampilkan teks
    } else {
        txtPassword.setEchoChar('•');         // sembunyikan lagi
    }
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
    new RegisterFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lblRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
