/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stayease.view;

/**
 *
 * @author malik
 */
import stayease.dao.UserDAO;
import stayease.model.User;
import stayease.util.Session;
import javax.swing.JOptionPane;
public class RegisterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFrame.class.getName());

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
    }
    
    /** Cek apakah username sudah dipakai. */
public boolean isUsernameTaken(String username) {
    String sql = "SELECT user_id FROM users WHERE username = ?";
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, username);
        try (ResultSet rs = ps.executeQuery()) {
            return rs.next();   // true kalau sudah ada
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return false;
}

/** Simpan user baru. Role otomatis 'user'. */
public boolean register(User user) {
    String sql = "INSERT INTO users (nama, username, password, role, email, no_telepon) "
               + "VALUES (?, ?, ?, 'user', ?, ?)";
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, user.getNama());
        ps.setString(2, user.getUsername());
        ps.setString(3, user.getPassword());
        ps.setString(4, user.getEmail());
        ps.setString(5, user.getNoTelepon());
        return ps.executeUpdate() > 0;   // true kalau berhasil
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return false;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        chkShowPassword = new javax.swing.JCheckBox();
        btnSignup = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(749, 451));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Create an account");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 210, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 30, 42, 42);

        jLabel4.setText("Fill in the following information to register");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 230, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("StayEase");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 30, 100, 30);

        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 150, 60, 16);

        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(50, 172, 220, 30);

        jLabel10.setText("Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 210, 60, 16);

        jLabel11.setText("Phone Number");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 270, 100, 16);

        txtTelepon.addActionListener(this::txtTeleponActionPerformed);
        getContentPane().add(txtTelepon);
        txtTelepon.setBounds(50, 290, 220, 30);

        chkShowPassword.setText("Show Password");
        chkShowPassword.addActionListener(this::chkShowPasswordActionPerformed);
        getContentPane().add(chkShowPassword);
        chkShowPassword.setBounds(50, 330, 120, 20);

        btnSignup.setBackground(new java.awt.Color(0, 153, 255));
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign up now");
        btnSignup.addActionListener(this::btnSignupActionPerformed);
        getContentPane().add(btnSignup);
        btnSignup.setBounds(50, 350, 220, 30);

        jLabel6.setText("Already have an account?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 390, 140, 16);

        lblLogin.setForeground(new java.awt.Color(0, 204, 255));
        lblLogin.setText("Login");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogin);
        lblLogin.setBounds(210, 390, 30, 16);

        txtPassword.setText("jPasswordField1");
        getContentPane().add(txtPassword);
        txtPassword.setBounds(50, 230, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register-form.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword());
    String telepon  = txtTelepon.getText().trim();

    // Peringatan 1: ada kolom kosong
    if (username.isEmpty() || password.isEmpty() || telepon.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return;
    }

    // Peringatan 2: password minimal 8 karakter
    if (password.length() < 8) {
        JOptionPane.showMessageDialog(this, "Password minimal 8 karakter!");
        return;
    }

    UserDAO dao = new UserDAO();

    // Peringatan 3: username sudah dipakai
    if (dao.isUsernameTaken(username)) {
        JOptionPane.showMessageDialog(this, "Username sudah digunakan!");
        return;
    }

    // Siapkan objek User (role otomatis 'user' di query DAO)
    User u = new User();
    u.setNama(username);          // form tak punya kolom Nama, pakai username
    u.setUsername(username);
    u.setPassword(password);
    u.setEmail(null);             // form tak punya kolom email
    u.setNoTelepon(telepon);      // Phone Number masuk ke no_telepon

    if (dao.register(u)) {
        JOptionPane.showMessageDialog(this, "Registrasi berhasil! Silakan login.");
        new LoginFrame().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Registrasi gagal, coba lagi.");
    }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
    new LoginFrame().setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoginMouseClicked

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSignup;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
